version: '3.8'

services:
  salesforce-csv-uploader:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SESSION_SECRET=${SESSION_SECRET}
      - SF_CLIENT_ID=${SF_CLIENT_ID}
      - SF_CLIENT_SECRET=${SF_CLIENT_SECRET}
      - SF_REDIRECT_URI=${SF_REDIRECT_URI}
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  uploads: